### PR TITLE
♻️ Fix clippy errors

### PR DESCRIPTION
**Pull request by clabby**
## Overview

> **Note**
> Stacked diff on top of #1, merge after it.

Fixes outstanding clippy errors.

### CODE REVIEW

**Comment by clabby** [comment]
Rebased on #1's merge into `main`.

**Comment by Philogy** [comment]
Dumb question but just for me to understand what does the change from `Vec<Asm>` to `[Asm]` here and there do? Is it just tidier or does it have some concrete safety/performance benefits?

**Comment by clabby** [comment]
Largely convention and flexibility for the API, but some perf benefits as well in certain cases (namely if you had a slice of `Asm`s, but needed to use these functions).

Converting a `&Vec<Asm>` (or an owned vec) to a slice (`&[Asm]`) doesn't require any allocation, but the other way around does. It's also easy to convert a `Vec` to a slice w/ `.as_slice()`. Generally, unless there's an explicit need for the `Vec`'s API / functionality, using slices over `Vec`s is preferred (clippy usually throws errors in most places here, which is helpful to get an intuition around it. `cargo +nightly clippy --all --all-features -- -D warnings` is a good general config for clippy in most projects)

**Comment by Philogy** [comment]
Thx! Makes sense.

**Pull request merged**
